services:
  # redis:
  #   image: redis:7.4.9-alpine
  #   ports:
  #     - "6379:6379"

  # ministack:
  #   image: ministackorg/ministack:1.3.31
  #   ports:
  #     - "4566:4566"
  #   environment:
  #     - PERSIST_STATE=0
  #     - S3_PERSIST=0
  #     - REDIS_HOST=redis
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

  # stackport:
  #   image: davireis/stackport:0.3.1
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - AWS_ENDPOINT_URL=http://ministack:4566
  #     - AWS_ACCESS_KEY_ID=test
  #     - AWS_SECRET_ACCESS_KEY=test
  #     - AWS_DEFAULT_REGION=ap-southeast-1
  #   depends_on:
  #     - ministack
  
  # AWS
  floci:
    image: floci/floci:2.1.0-compat
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # # Azure
  # floci-az:
  #   image: floci/floci-az:0.13.0-compat
  #   ports:
  #     - "4577:4577"

  # # GCP
  # floci-gcp:
  #   image: floci/floci-gcp:0.9.0-compat
  #   ports:
  #     - "4588:4588"
